name: Ruff CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Запуск проверки кода (Линтер)
      - name: Run Ruff Check
        uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "check ."

      # Запуск проверки стиля кода (Форматтер)
      - name: Run Ruff Format
        uses: astral-sh/ruff-action@v4.1.0
        with:
          args: "format --check ."
